### ISSUE TITLE
Strange PEM routines error

### ISSUE THREAD

**Issue by d-ivashchuk** [daveagill/verify-paddle-webhook#3]
First of all big thanks for abstracting this into a separate package. This is probably unrelated to the library itself, but maybe you will have answer for this. Fighting to verify paddle webhook for some time and no luck. Both with my own implementation and your library I get this error:

```
Error: error:0909006C:PEM routines:get_name:no start line
    at Verify.verify (internal/crypto/sig.js:183:24)
    at exports.verifyPaddleWebhook (/Users/d-ivashchuk/projects/twitastic/twitastic-backend/node_modules/verify-paddle-webhook/index.js:43:25)
    at /Users/d-ivashchuk/projects/twitastic/twitastic-backend/src/index.js:25:3
    at Layer.handle [as handle_request] (/Users/d-ivashchuk/projects/twitastic/twitastic-backend/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/d-ivashchuk/projects/twitastic/twitastic-backend/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/d-ivashchuk/projects/twitastic/twitastic-backend/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/d-ivashchuk/projects/twitastic/twitastic-backend/node_modules/express/lib/router/layer.js:95:5)
    at /Users/d-ivashchuk/projects/twitastic/twitastic-backend/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/Users/d-ivashchuk/projects/twitastic/twitastic-backend/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/d-ivashchuk/projects/twitastic/twitastic-backend/node_modules/express/lib/router/index.js:275:10)
    at /Users/d-ivashchuk/projects/twitastic/twitastic-backend/node_modules/body-parser/lib/read.js:130:5
    at invokeCallback (/Users/d-ivashchuk/projects/twitastic/twitastic-backend/node_modules/raw-body/index.js:224:16)
    at done (/Users/d-ivashchuk/projects/twitastic/twitastic-backend/node_modules/raw-body/index.js:213:7)
    at IncomingMessage.onEnd (/Users/d-ivashchuk/projects/twitastic/twitastic-backend/node_modules/raw-body/index.js:273:7)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1221:12) {
  library: 'PEM routines',
  function: 'get_name',
  reason: 'no start line',
  code: 'ERR_OSSL_PEM_NO_START_LINE'
}
```

I would very much appreciate any directions or help, as I am really stuck with this 😬 Thanks a lot!

**Comment by daveagill** [comment]
Most likely it's an issue with your public key.

Normally that error might indicate that your public key does not have the PEM header line: `-----BEGIN PUBLIC KEY-----` or the newline after the header might be missing.

**Comment by daveagill** [comment]
@d-ivashchuk Any luck getting to the bottom of this?  If there's nothing else I'll close this ticket (as it's seemingly not an issue specific to this lib).

**Comment by d-ivashchuk** [comment]
I've fixed it not so long ago. The issue was with how my prettier formatted the code - if anyone will see this error. Leaving the start and end parts + making sure it's stored correctly fixed the issue! Thanks a lot 👍🏼
